version: 2.1
orbs:
  ruby-rails: sul-dlss/ruby-rails@1.1.0
workflows:
  build:
    jobs:
      - ruby-rails/validate-api:
          name: validate
      - ruby-rails/lint:
          name: lint
      - ruby-rails/test-gem:
          name: test
