# Form source codes from LC source lists
# Sources:
# - https://www.loc.gov/standards/sourcelist/genre-form.html
# - https://www.loc.gov/standards/sourcelist/subject.html
- aass
- aat
- aatnor
- abne
- aedoml
- afo
- afset
- agrifors
- agrovoc
- agrovocf
- agrovocs
- ahecc
- aiatsisl
- aiatsisp
- aiatsiss
- aktp
- albt
- alett
- allars
- amg
- anzsic
- anzsoc
- anzsrc
- apaist
- armarc
- ascdc
- asced
- ascl
- asft
- ashlnl
- asrcrfcd
- asrcseo
- asrctoa
- asth
- ated
- atg
- atla
- aucsh
- ausext
- bare
- barn
- barngf
- bdrc
- bella
- bellobv
- bet
- bgtchm
- bhammf
- bhashe
- bhb
- bib1814
- bibalex
- bibbi
- biccbmc
- bicssc
- bidex
- bisacmt
- bisacrt
- bisacsh
- bjornson
- blcpss
- blmlsh
- blnpn
- bokbas
- bt
- btr
- buscem
- buscxf
- cabt
- cash
- cbk
- cbktrf
- cccv
- cck
- cckthema
- ccsa
- cct
- ccte
- cctf
- cdcng
- ceeus
- cgndb
- cgpa
- chirosh
- cht
- ciesiniv
- cilla
- cjh
- coarrt
- collett
- conorsi
- conorsr
- csahssa
- csalsct
- csapa
- csh
- csht
- cstud
- cyac
- czenas
- czmesh
- dbcsh
- dbn
- dcs
- dct
- ddcri
- ddcrit
- ddcut
- dhb-jdg
- dicgenam
- dicgenes
- dicgentop
- dissao
- dit
- dltlt
- dltt
- doll
- drama
- dtict
- dugfr
- ebfem
- eclas
- eet
- eflch
- eks
- elsst
- embehu
- embiaecid
- embne
- embucm
- embus
- embuz
- emnmus
- ept
- erfemn
- ericd
- esar
- est
- estc
- etiras
- etuesh
- etuturkob
- eum
- eurovoc
- eurovocen
- eurovoces
- eurovocfr
- eurovocsl
- fast
- fbg
- fcb
- fes
- fgtpcm
- finmesh
- fire
- flgeo
- fmesh
- fnhl
- francis
- frst
- fssh
- ftamc
- galestne
- gatbeg
- gbd
- gccst
- gcipmedia
- gcipplatform
- gem
- gemet
- gemppg
- geni
- geonames
- geonet
- georeft
- gmd
- gmgpc
- gnd
- gnd-carrier
- gnd-content
- gnd-music
- gnis
- gpn
- gsafd
- gsso
- gst
- gtlm
- gtmm
- gtt
- gttg
- habibe
- habich
- habifr
- habiit
- hamsun
- hapi
- helecon
- henn
- hkcan
- hlasstg
- hoidokki
- homoit
- hrvmesh
- hrvmr
- huc
- humord
- ibsen
- ica
- iconauth
- icpsr
- idas
- idref
- idsbb
- idszbz
- idszbzes
- idszbzna
- idszbzzg
- idszbzzh
- idszbzzk
- iescs
- iest
- ilot
- ilpt
- inist
- inspect
- ipat
- ipsp
- iptcnc
- isbdcontent
- isbdmedia
- isis
- itglit
- itis
- itrt
- jhpb
- jhpk
- jlabsh
- juho
- jupo
- jurivoc
- kaa
- kaba
- kao
- kassu
- kauno
- kaunokki
- kdm
- khib
- kito
- kitu
- kkts
- koko
- kssbar
- kta
- kto
- ktpt
- ktta
- kubikat
- kula
- kulo
- kupu
- labloc
- lacnaf
- lapponica
- larpcal
- lcac
- lcdgt
- lcgft
- lcmpt
- lcsh
- lcshac
- lcstt
- lctgm
- leaubsh
- lemac
- lemb
- liito
- liv
- lnmmbr
- lobt
- local
- lst
- ltcsh
- lua
- maaq
- maknaz
- maotao
- mar
- marccarrier
- marccategory
- marcform
- marcgt
- marcsmd
- masa
- mech
- mero
- mesh
- meshscr
- migfg
- mim
- minecost
- mipfesd
- mmm
- mpirdes
- msc
- msh
- msupplcont
- mtirdes
- mts
- musa
- muso
- musvok-sf
- muzeukc
- muzeukn
- muzeukv
- muzvukci
- naf
- nal
- nalnaf
- nasat
- nbdbgf
- nbdbt
- nbiemnfag
- ncjt
- ncrbs
- ncrcarrier
- ncrcontent
- ncrcpc
- ncrfs
- ncrft
- ncrmat
- ncrmedia
- ncrpm
- ncrpo
- ncrrm
- ncrtr
- ncrvf
- ndlgft
- ndlsh
- neo
- netc
- ngl
- nicem
- nimacsc
- nimafc
- niodt
- nlgaf
- nlggf
- nlgkk
- nlgsh
- nli
- nlksh
- nlmnaf
- nmaict
- nmc
- no-ubo-mr
- nom
- noraf
- noram
- norbok
- normesh
- norvok
- noubojur
- noubomn
- nsbncf
- nskps
- nskzs
- nta
- ntc
- ntcpsc
- ntcsd
- ntids
- ntissc
- ntsf
- nzcoh
- nzggn
- nznb
- oabt
- odlt
- ogst
- olacvggt
- opat
- opms
- ordnok
- orgnr
- pana
- pascal
- peakbag
- pepp
- peri
- periodo
- pha
- pkk
- pldi
- pleiades
- pmbok
- pmcsg
- pmont
- pmt
- poha
- poliscit
- popinte
- pplt
- ppluk
- precis
- prnpdi
- proqsc
- proysen
- prvt
- psh
- psychit
- puho
- qlit
- qlsp
- qnaf
- qnlsh
- qrma
- qrmak
- qtglit
- quiding
- radfg
- ram
- rasuqam
- rbbin
- rbgenr
- rbmscv
- rbpap
- rbpri
- rbprov
- rbpub
- rbtyp
- rda
- rdaar
- rdabf
- rdabs
- rdacarrier
- rdacc
- rdaco
- rdacontent
- rdacpc
- rdact
- rdaep
- rdafmn
- rdafnm
- rdafr
- rdafs
- rdaft
- rdagen
- rdagrp
- rdagw
- rdaill
- rdalay
- rdamat
- rdamedia
- rdami
- rdamt
- rdapf
- rdapm
- rdapo
- rdare
- rdarm
- rdarr
- rdasco
- rdaspc
- rdatb
- rdatc
- rdatr
- rdavf
- renib
- reo
- rero
- rerovoc
- reveal
- rma
- root
- rpe
- rswk
- rswkaf
- rugeo
- rurkp
- rvm
- rvmfast
- rvmgd
- rvmgf
- samisk
- sanb
- sao
- saogf
- sbaa
- sbiao
- sbt
- scbi
- scgdst
- scisshl
- scot
- sears
- sesca
- sfit
- sgc
- sgce
- sgp
- shbe
- she
- shsples
- sigle
- sipri
- sk
- skbb
- skish
- skon
- slem
- slm
- smda
- snt
- socio
- solstad
- sosa
- soto
- spines
- ssg
- stcv
- sthus
- stw
- swd
- swemesh
- taika
- tasmas
- taxhs
- tbjvp
- tef
- tekord
- tept
- tero
- tesa
- tesbhaecid 
- test
- tgfbne
- tgfc
- tgn
- tha
- thema
- thesoz
- thia
- thla
- tho
- thub
- tips
- tisa
- tlka
- tlsh
- tmdbm
- tmdbp
- tmdbtv
- tpro
- trfarn
- trfbmb
- trfdh
- trfgr
- trfoba
- trfzb
- trt
- trtsa
- tsaij
- tshd
- tsht
- tsr
- ttka
- ttll
- tucua
- udc
- ukslc
- ula
- ulan
- umitrist
- unbisn
- unbist
- unescot
- unicefirc
- usaidt
- usgst
- valo
- vcaadu
- vffyl
- vgmsgg
- vgmsng
- vmj
- waqaf
- watrest
- wgst
- wikidata
- worldcat
- wot
- wpicsh
- ysa
- yso
- zst
