# LC Standard Identifier Source Codes
# Source: https://www.loc.gov/standards/sourcelist/standard-identifier.html
# Additional codes: swets, apis
- agorha
- agrovoc
- allmovie
- allmusic
- allocine
- amnbo
- ansi
- apis
- archinl
- archinpe
- archinpr
- archna
- archns
- ark
- artsy
- artukart
- artukaw
- atg
- balat
- bbcth
- bdrc
- bdusc
- belvku
- belvwrk
- benezit
- bew
- bfi
- bibbi
- bigenc
- bnfcg
- bpn
- bsi
- cabt
- cana
- cantic
- cbwpid
- cerl
- cgndb
- clara
- cnbksy
- csfdcz
- danacode
- darome
- datoses
- discogs
- dkfilm
- dma
- doi
- dpb
- ean
- ecli
- eidr
- emlo
- fast
- fidecp
- filmaff
- filmport
- findagr
- fisa
- freebase
- fuoc
- gacsch
- gec
- geogndb
- geonames
- geprishisp
- gettyaat
- gettyart
- gettyobj
- gettytgn
- gettyulan
- gnd
- gnis
- goodra
- gtaa
- gtin-14
- hdl
- iaafa
- ibdb
- iconauth
- idref
- imdb
- isan
- isbn
- isbn-a
- isbnre
- isbnsbn
- isfdbau
- isfdbaw
- isfdbma
- isfdbpu
- isil
- ismn
- isni
- iso
- isrc
- issn
- issn-l
- issue-number
- istc
- iswc
- it-acnp
- itar
- kda
- kdw
- kinopo
- knpam
- kulturnav
- lattes
- lccn
- lcmd
- lcmpt
- lei
- libaus
- lmhl
- local
- margaz
- matrix-number
- mesh
- mocofo
- moma
- morana
- moviemetf
- moviemetr
- munzing
- muscl
- music-plate
- music-publisher
- musicb
- nacat
- nagb
- natgazfid
- nga
- ngva
- ngvw
- nipo
- nlg
- nndb
- npg
- nzggn
- odnb
- ofdb
- onix
- opensm
- orcid
- orgnr
- oxforddnb
- pcadbu
- pcadpe
- pcadpf
- permid
- picnypl
- pleiades
- pnta
- porthu
- prabook
- rbmsbt
- rbmsgt
- rbmspe
- rbmsppe
- rbmspt
- rbmsrd
- rbmste
- rid
- rkda
- ror
- s2a3bd
- saam
- scholaru
- scope
- scopus
- sici
- smgp
- snac
- spotify
- sprfbsb
- sprfbsk
- sprfcbb
- sprfcfb
- sprfhoc
- sprfoly
- sprfpfb
- ssaut
- stock-number
- strn
- stw
- svfilm
- swets
- tatearid
- theatr
- tpce
- trove
- unescot
- upc
- uri
- urn
- vd16
- vd17
- vd18
- vgmdb
- viaf
- videorecording-identifier
- wikidata
- wndla
- xgamea
- ysopai
- zbaut
