# Language Code and Term Source Codes
# Source: https://www.loc.gov/standards/sourcelist/language.html
- austlang
- din2335
- glotto
- iso639-1
- iso639-2b
- iso639-3
- iso639-5
- knia
- lrwl
- rfc3066
- rfc4646
- rfc5646
- walso
